### ISSUE TITLE
Phaser container support

### ISSUE THREAD

**Issue by borkowsky** [Annoraaq/phaser-grid-movement-plugin#40]
Hi. I want suggest to add for containers support. It will be useful for character sprite with name.

**Comment by Annoraaq** [comment]
That's a good suggestion and also a good use case. I haven't thought about it.

**Comment by Annoraaq** [comment]
@borkowsky I just added container support with the new release. Check out the following example as well as the updated readme. https://github.com/Annoraaq/phaser-grid-movement-plugin/blob/master/examples/container/index.html

Please note that you need to position the sprite at position (0, 0) in the container for the positioning of the player on the tiles to work correctly.

**Comment by borkowsky** [comment]
Im happy now, thank you 😊
