### ISSUE TITLE
One-way collision detection

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/phaser-grid-movement-plugin#46]
Hey there! Love the project, happy to see grid based movement get the love it deserves.

One improvement I think would help significantly is Tiled custom properties support for one-way collision, i.e. I can set `collideOnly: UP` to a tile and so you can walk through it from any direction but the top.

I'll also try and look into contributing on this idea as well.

Thanks!

**Comment by Annoraaq** [comment]
Hi @splashsky, thank you. It is great to hear you like the project!

I think it's a great idea. I will set it up for the next milestone 🚀

**Comment by Annoraaq** [comment]
Changes are merged on master and will be in 1.6.0 release.

Documentation is here:

https://github.com/Annoraaq/phaser-grid-movement-plugin/wiki/Tile-Properties

An example can be found here:
https://annoraaq.github.io/phaser-grid-movement-plugin/examples/

**Comment by Annoraaq** [comment]
@splashsky a new version 1.6.0 is now live including the one-way collision
