### ISSUE TITLE
gm_alwaysTop property bug

### ISSUE THREAD

**Issue by borkowsky** [Annoraaq/phaser-grid-movement-plugin#53]
Hi. I have tilemap with 3 layers: ground, misc1 and misc2. Layer **misc2** have property **gm_alwaysTop** with checked checkbox. But layer **misc1** rendered at the top of player instead of **misc2**. Layer **misc1** not have any properties.

**Comment by borkowsky** [comment]
Misc1 layer parameters: https://prntscr.com/10elnwp
Misc2 layer parameters: https://prntscr.com/10ellfr
Result: https://prntscr.com/10eljn7
Road placed at misc1 layer.

**Comment by Annoraaq** [comment]
Hi @borkowsky.

Thank you for reporting.

I will try to reproduce. Are you in addition using the `firstLayerAboveChar` option? (https://github.com/Annoraaq/phaser-grid-movement-plugin/wiki/Config)

I will let you know as soon as I found out something.

**Comment by borkowsky** [comment]
No, i deleted this properties, because its deprecated.

**Comment by Annoraaq** [comment]
Hey @borkowsky, I am not able to reproduce the bug. I created a small map with 3 layers and gave the top one the property and it works. Can you try to clean your browser cache? It caches the tilemaps.

**Comment by borkowsky** [comment]
Hello. Unfortunately,  clearing browser's cache not solved the problem. I think, i need roll back to using firstLayerAboveChar property.

**Comment by borkowsky** [comment]
Even firstLayerAboveChar not working...

**Comment by borkowsky** [comment]
Oh god, it was my silly mistake... I add container but not let main camera to start follow him, and not add to character configuration. Im sorry.

**Comment by Annoraaq** [comment]
No need to apologize :) I'm glad your problem is solved.

I assume the depth (z-index) did not work,  because the container was not passed to the config.
