### ISSUE TITLE
Need branch for documentation update

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/phaser-grid-movement-plugin#63]
Hey there! I'm ready to submit a PR for the big documentation update. We're going to need a `gh-pages` branch that's empty so we can merge the site directly over. The repository should also be set up to serve the Pages site from the `gh-pages` / (root).

Will be happy to continue contributing to documentation as time goes forward, including the API documentation I'm still working on. 😄

**Comment by splashsky** [comment]
As an additional note - it will no longer be required to have the `docs/` folder present in the `master` branch either. All examples, images and scripts needed for the documentation will be present in the `gh-pages` branch.

**Comment by Annoraaq** [comment]
Hi splashsky, I just created that empty branch. Can you create a PR to that branch and then I will redirect gh pages to point to that branch.
