### ISSUE TITLE
Support isometric maps

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/phaser-grid-movement-plugin#82]

**Comment by splashsky** [comment]
Just as a quick note - it might be really easy to convert the top-down (orthogonal) features of the plugin to isometric - isometric is just orthogonal with a half-offset and a rotational shift to simulate being angled. There are a myriad of articles on this, but if it's not on the roadmap now that's alright.

**Comment by Annoraaq** [comment]
I think you are right. A rotation of the movement direction vectors should do most of the work. Then there are the tiny things that can make it a bit harder but it s probably not as big of a change as I first suspected.

**Comment by neu5** [comment]
@Annoraaq are you going to keep top/right/down/left directions or you're planning to extend them of top-right etc. for isometric?
IMO in top-down games it's natural to move only in those four directions but in isometric it's tempting to have more freedom in the movement.

**Comment by Annoraaq** [comment]
@neu5 In the first step it will only be the 4 directions.

In the future the plugin might also support more directions.

**Comment by Annoraaq** [comment]
@neu5 isometric map support is now available with 1.11 release.

However, it is still in beta and there might be some bugs that will only show in real situations. If you find any issues, please let us know.
