### ISSUE TITLE
Adding players on the go

### ISSUE THREAD

**Issue by borkowsky** [Annoraaq/phaser-grid-movement-plugin#9]
Hi. Can i add more players when they r appeared at current location? I want create realtime rpg

**Comment by Annoraaq** [comment]
Hey borkowsky, It is not yet possible in a non-hacky way. But I think it would be really useful. I will make sure this issue get implemented and released asap.

**Comment by Annoraaq** [comment]
Merged this to master. I will add some minor error reporting functionality to the plugin and create a new release.

**Comment by Annoraaq** [comment]
You can now find a new version (1.2.0) online on npm.

@borkowsky I am interested in your project. So if you like, let me know about it. And please keep giving me feedback about the plugin so I know which features are needed most.

**Comment by borkowsky** [comment]
Hi, sure. My project in development now, i will upload in months. Thank you for make it for us
